# Background and foreground colors
background = #0d0a0e
foreground = #ebe7ee

# Standard colors
palette = 0=#0d0a0e
palette = 1=#a169bf
palette = 2=#ab6acd
palette = 3=#b07acc
palette = 4=#a557ce
palette = 5=#ac77c8
palette = 6=#b884d4
palette = 7=#d2ccd6

# Bright colors
palette = 8=#7a5c8a
palette = 9=#caa7dd
palette = 10=#d3ace7
palette = 11=#d8bae7
palette = 12=#bb65e9
palette = 13=#c285e2
palette = 14=#ce96eb
palette = 15=#ebe7ee
