background            #0d0a0e
foreground            #ebe7ee

# black
color0  #0d0a0e
color8  #7a5c8a

# red
color1  #a169bf
color9  #caa7dd

# green
color2  #ab6acd
color10 #d3ace7

# yellow
color3  #b07acc
color11 #d8bae7

# blue
color4  #a557ce
color12 #bb65e9

# magenta
color5  #ac77c8
color13 #c285e2

#cyan
color6  #b884d4
color14 #ce96eb

#white
color7  #d2ccd6
color15 #ebe7ee


