# Background and foreground colors
background = #18131a
foreground = #f1eef2

# Standard colors
palette = 0=#18131a
palette = 1=#ac69bf
palette = 2=#b86acd
palette = 3=#bb7acc
palette = 4=#b557ce
palette = 5=#b677c8
palette = 6=#c384d4
palette = 7=#d9d2db

# Bright colors
palette = 8=#805c8a
palette = 9=#d1a7dd
palette = 10=#daace7
palette = 11=#debae7
palette = 12=#cd65e9
palette = 13=#ce85e2
palette = 14=#d996eb
palette = 15=#f1eef2
