background            #18131a
foreground            #f1eef2

# black
color0  #18131a
color8  #805c8a

# red
color1  #ac69bf
color9  #d1a7dd

# green
color2  #b86acd
color10 #daace7

# yellow
color3  #bb7acc
color11 #debae7

# blue
color4  #b557ce
color12 #cd65e9

# magenta
color5  #b677c8
color13 #ce85e2

#cyan
color6  #c384d4
color14 #d996eb

#white
color7  #d9d2db
color15 #f1eef2


