# Application bindings
$terminal = ghostty
$browser = brave-browser

unbind = SUPER, W
bindd = SUPER, Q, Close Window, killactive,
bindd = SUPER, return, Terminal, exec, $terminal --working-directory=$(omarchy-cmd-terminal-cwd)
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, N, Neovim, exec, $terminal -e nvim
bindd = SUPER, T, Activity, exec, $terminal -e btop
bindd = SUPER, D, Docker, exec, $terminal -e lazydocker

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER, W, WhatsApp, exec, omarchy-launch-webapp "https://web.whatsapp.com/"

# unbind = SUPER, SPACE

bind = SUPER, bracketleft, focusmonitor, -1
bind = SUPER, bracketright, focusmonitor, +1


# bindd = ALT, tab, Cycle to next window, cyclenext

unbind = SUPER, K
unbind = SUPER, J
unbind = SUPER, H
unbind = SUPER, L
#Move focus
bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d

bindd = ALT, return, Force full screen, fullscreen, 0


# Resize active window
bindd = SUPER SHIFT,H, Expand window left, resizeactive, -100 0    # - key
bindd = SUPER SHIFT,L, Shrink window left, resizeactive, 100 0     # = key
bindd = SUPER SHIFT,K, Shrink window up, resizeactive, 0 -100
bindd = SUPER SHIFT,J, Expand window down, resizeactive, 0 100

#Moving entie workspace to another focusmonitor
bind = SUPER SHIFT, bracketleft,  movecurrentworkspacetomonitor, -1
bind = SUPER SHIFT, bracketright, movecurrentworkspacetomonitor, +1

# External-only workspace navigation (always acts on external)
bindd = SUPER ALT, L,  Next workspace on external, exec, ~/.config/hypr/user_overrides/scripts/ws-ext-next
bindd = SUPER ALT,H,   Prev workspace on external, exec,  ~/.config/hypr/user_overrides/scripts/ws-ext-prev

bindd = SUPER ALT, right,  Next workspace on external, exec, ~/.config/hypr/user_overrides/scripts/ws-ext-next
bindd = SUPER ALT,left,   Prev workspace on external, exec,  ~/.config/hypr/user_overrides/scripts/ws-ext-prev

bindd = SUPER CTRL ALT, L, Send window to next ws (ext) + follow, exec, ~/.config/hypr/user_overrides/scripts/send-to-ext-next-and-follow
bindd = SUPER CTRL ALT, H, Send window to prev ws (ext) + follow, exec,  ~/.config/hypr/user_overrides/scripts/send-to-ext-prev-and-follow

bindd = SUPER CTRL ALT, right, Send window to next ws (ext) + follow, exec, ~/.config/hypr/user_overrides/scripts/send-to-ext-next-and-follow
bindd = SUPER CTRL ALT, left, Send window to prev ws (ext) + follow, exec,  ~/.config/hypr/user_overrides/scripts/send-to-ext-prev-and-follow

#Screenshots
bindd = SUPER SHIFT, S, Screenshot of region, exec, omarchy-cmd-screenshot

bindd = SUPER SHIFT, V, Screen record a region, exec, omarchy-cmd-screenrecord

bindd = ALT SHIFT, S, Screen record a display,  exec, omarchy-cmd-screenrecord output


# Manual “fix it now” toggle when you plug/unplug
bind = SUPER ALT,P, exec, ~/.config/hypr/user_overrides/scripts/hypr-profile auto

# If you want hard overrides too:
bind = SUPER ALT,M, exec, ~/.config/hypr/user_overrides/scripts/hypr-profile docked
bind = SUPER ALT,L, exec, ~/.config/hypr/user_overrides/scripts/hypr-profile laptop


# Fix duplicate binds
unbind = SUPER, T

